### ISSUE TITLE
Initial use obstacles 

### ISSUE THREAD

**Issue by vitch** [isleofcode/ember-cordova-splash#1]
I've just upgraded an old project from `ember-cli-cordova` to `ember-cordova` and tried to follow the instructions for `ember-cordova-splash` but I ran into a couple of issues:

 1. It seems to be necessary to `ember cdv:plugin add cordova-plugin-splashscreen` to get it to work at all?
 2. The documentation [here](http://embercordova.com/pages/addons/splash) gives the incorrect service path (`splashscreenService: service('device/splashscreen')` rather than `splashscreenService: service('ember-cordova/splash')`).
 3. When I build my app with the `--release` flag the slash screen doesn't seem to be hidden by calling `this.get('splashScreenService').hide()` - the splash screen and a spinner remain on screen

I will investigate the third issue further and provide an update if I figure anything out but I was wondering if these were issues anyone else had run into?

**Comment by vitch** [comment]
I suspect that the third issue is a race condition where deviceReady has fired before I call `hide` on the splash screen although I'm not certain. The deprecated version (which uses `cordova.ready`) seems to work reliably...

**Comment by alexblom** [comment]
Apologies on the delay - notifications on sub repos were not optimal and I missed a few things.

I've since made some updates to the plugin that should resolve the issues you were having, likely with the plugin not being default installed. There shouldn't be an issue with the deviceready firing, as it will fire immediately in circumstances where the device is already ready.

Is this issue persisting for you?

**Comment by alexblom** [comment]
Closing - but please re open if the comment above did not help.
