### ISSUE TITLE
Needs corber updates?

### ISSUE THREAD

**Issue by OakBehringer** [isleofcode/ember-cordova-splash#8]
Using with corber...

`ember install ember-cordova-splash`

... results in ...

```
NPM: Installed ember-cordova-splash
installing ember-cordova-splash
ember-cordova plugin error:
        Can not install cordova-plugin-splashscreen as ember-cordova is not installed
```

Using current version of corber... thanks!

**Comment by vitch** [comment]
Seems to be down to [this](https://github.com/isleofcode/ember-cordova-splash/blob/master/blueprints/ember-cordova-splash/index.js#L11) usage of [ember-cordova-installer](https://github.com/isleofcode/ember-cordova-installer/) which checks for the presence of `ember-cordova` and uses `ember cdv:plugin add x` rather than `corber plugin add x`

**Comment by vitch** [comment]
If you ignore the error and manually `corber plugin add cordova-plugin-splashscreen` then it seems to work OK
